services:
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  app:
    build: .
    restart: always
    command: python3 main.py
    depends_on:
      - db
    ports:
      - "8080:8080"
